apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: py-app
  namespace: flux-system
spec:
  image: docker.io/alii2121/py-app
  interval: 30s
  secretRef:
    name: docker-sec

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: py-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: py-app
    namespace: flux-system
  filterTags:
    pattern: 'main-.*'
  policy:
    semver:
      range: '>=1'
