apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: py-app
  namespace: flux-system
spec:
  image: docker.io/alii2121/py-app
  interval: 5m
  secretRef:
    name: docker-sec

---

apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: py-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: py-app
    namespace: flux-system
  policy:
    semver: {}
  automated: true
  tagPattern: "main-*"
  registry:
    url: https://index.docker.io/v1/
    credentialsRef:
      name: dockerhub-credentials
