apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps
  prune: true
  validation: client

# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: flux-system
#   namespace: flux-system
# spec:
#   interval: 1m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: "./infra"
#   prune: true
#   timeout: 1m
# ---
