apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: '6.0.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 1m
  values:
    replicaCount: 1
