apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- /home/ali.marwan@ad.cyshield/GIT-OPS-FLUX/GitOps-fluxCD/apps/base/nginx
- /home/ali.marwan@ad.cyshield/GIT-OPS-FLUX/GitOps-fluxCD/apps/Prod/nginx


